### ISSUE TITLE
Can't build ognbase.ino.esp32_TTGO_V0.1.0-26.bin from source

### ISSUE THREAD

**Issue by CazYokoyama** [roema/Open-Glider-Network-Groundstation#26]
TTGO PaxCounter has arrived. The binary can't be installed by web IF because Its pre-installed software, PaxCounter does not have web IF. Source build by arduino has error as the png file. I am glad if someone tells me what I missed.

![DSC_0010](https://user-images.githubusercontent.com/2885042/141015655-e81b7488-2218-47bc-952a-383c8394bc84.JPG)
![DSC_0013](https://user-images.githubusercontent.com/2885042/141015660-cbdacc5b-5c86-4201-96a4-f6ae8717a22d.JPG)
![LoRa32-OLED-v2 1 6](https://user-images.githubusercontent.com/2885042/141015889-3443e46a-daef-498b-92d0-3abeb9c2ecc3.png)

**Comment by roema** [comment]
Hi Caz!Usw the same compile options and board like T-Beam. The only different ist the psram. Set it to disable.Am 09.11.2021 23:33 schrieb CazYokoyama ***@***.***>:
TTGO PaxCounter has arrived. The binary can't be installed by web IF because Its pre-installed software, PaxCounter does not have web IF. Source build by arduino has error as the png file. I am glad if someone tells me what I missed.

**Comment by CazYokoyama** [comment]
With the direction above, I successfully build, install, configure PaxCounter.

**Comment by schenlap** [comment]
Ich habe hier das selbe Problem.

```
Sketch uses 1338226 bytes (102%) of program storage space. Maximum is 1310720 bytes.text section exceeds available space in board

Global variables use 60696 bytes (18%) of dynamic memory, leaving 266984 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
Error compiling for board T-Beam.
```

With enabled psram i get 108% instead of 102%.

![image](https://user-images.githubusercontent.com/20611587/160241681-fa589514-a937-43a8-959f-a66fb957e7ca.png)
